### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by benogle** [tvooo/scope-inspector#12]
_From @dharmax on December 11, 2014 10:45_

Uncaught Error: This TextEditor has been destroyed

**Atom Version**: 0.154.0
**System**: linux 3.13.0-40-generic
**Thrown From**: [scope-inspector](https://github.com/tvooo/scope-inspector) package

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /opt/atom/resources/app/src/display-buffer.js:989

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/opt/atom/resources/app/src/display-buffer.js:989:15)
  at Marker.module.exports.Marker.getHeadScreenPosition (/opt/atom/resources/app/src/marker.js:211:33)
  at new Marker (/opt/atom/resources/app/src/marker.js:45:41)
  at DisplayBuffer.module.exports.DisplayBuffer.getMarker (/opt/atom/resources/app/src/display-buffer.js:1212:20)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/opt/atom/resources/app/src/display-buffer.js:1244:19)
  at TextEditor.module.exports.TextEditor.markBufferRange (/opt/atom/resources/app/src/text-editor.js:1251:59)
  at Inspection.module.exports.Inspection.updateMarkers (/home/avit/.atom/packages/scope-inspector/lib/inspection.coffee:73:24)
  at Inspection.module.exports.Inspection.onSaved (/home/avit/.atom/packages/scope-inspector/lib/inspection.coffee:138:6)
  at delayed (/opt/atom/resources/app/node_modules/markdown-preview/node_modules/cheerio/node_modules/lodash/dist/lodash.js:5408:27)

```

_Copied from original issue: atom/atom#4539_

**Comment by tvooo** [comment]
Was fixed by f0f53b43ea93fb5431ac32ae8d56068d6f98455f
