### ISSUE TITLE
Uncaught TypeError: Cannot read property 'editor' of undefined

### ISSUE THREAD

**Issue by benogle** [tvooo/scope-inspector#13]
_From @dharmax on December 11, 2014 11:36_

Uncaught TypeError: Cannot read property 'editor' of undefined

**Atom Version**: 0.154.0
**System**: linux 3.13.0-40-generic
**Thrown From**: [scope-inspector](https://github.com/tvooo/scope-inspector) package

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /home/avit/.atom/packages/scope-inspector/lib/scope-inspector-view.coffee:60

TypeError: Cannot read property 'editor' of undefined
  at ScopeInspectorView.module.exports.ScopeInspectorView.onClickIdentifier (/home/avit/.atom/packages/scope-inspector/lib/scope-inspector-view.coffee:60:29)
  at HTMLLIElement.<anonymous> (/home/avit/.atom/packages/scope-inspector/lib/scope-inspector-view.coffee:21:41)
  at HTMLLIElement.handler (/opt/atom/resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDivElement.jQuery.event.dispatch (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

_Copied from original issue: atom/atom#4540_

**Comment by tvooo** [comment]
Was fixed by 0586fa52042efda1aef0f0d795a071bd6ca4581e
