### ISSUE TITLE
Uncaught TypeError: Cannot read property 'editor' of null

### ISSUE THREAD

**Issue by kreo** [tvooo/scope-inspector#19]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [scope-inspector](https://github.com/tvooo/scope-inspector) package, v1.0.1
### Stack Trace

Uncaught TypeError: Cannot read property 'editor' of null

```
At /Users/mac/.atom/packages/scope-inspector/lib/scope-inspector-view.coffee:54

TypeError: Cannot read property 'editor' of null
  at ScopeInspectorView.module.exports.ScopeInspectorView.onClickIdentifier (/Users/mac/.atom/packages/scope-inspector/lib/scope-inspector-view.coffee:54:29)
  at HTMLLIElement.<anonymous> (/Users/mac/.atom/packages/scope-inspector/lib/scope-inspector-view.coffee:23:41)
  at space-pen-div.jQuery.event.dispatch (/Applications/dev/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/Applications/dev/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4116:28)

```
### Commands

```
```
### Config

``` json
{
  "core": {},
  "scope-inspector": {
    "userId": "d32eda0cc59a2e316bad354c4352969f38cac493"
  }
}
```
### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-django, v0.2.1
autocomplete-python, v0.1.5
color-picker, v1.7.0
django-templates, v0.4.0
language-django, v0.1.1
language-python-django-templates, v0.1.0
linter, v0.12.1
linter-python-pep8, v0.2.0
minimap, v4.7.6
scope-inspector, v1.0.1
travis-ci-status, v0.13.0
virtualenv, v0.6.2

# Dev
No dev packages
```

**Comment by SecureCloud-biz** [comment]
Same.... Please Fix..
